# src/rn/mkdocs_publish.py
"""
MkDocs publishing utilities.

Purpose:
- Publish generated release notes into a MkDocs-compatible docs/ directory.
- Auto-generate mkdocs.yml navigation based on the configured target languages.

Why this matters:
- MkDocs produces a fully static site (site/) that is easy to preview (`mkdocs serve`)
  and easy to deploy on any static hosting (S3, GitHub Pages, internal servers).
- Auto-generating mkdocs.yml keeps navigation consistent with the language set
  without manual edits (configuration-driven publishing).
"""
from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Optional

# Default MkDocs configuration blocks.
# Kept as plain YAML strings to avoid adding extra dependencies (e.g., PyYAML).
DEFAULT_THEME_BLOCK = """theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
"""

# Minimal Markdown extensions: toc + admonition are common and improve readability.
DEFAULT_MD_EXTENSIONS_BLOCK = """markdown_extensions:
  - admonition
  - toc:
      permalink: true
"""

# Search plugin enables fast navigation in the static site (good UX even for small docs).
DEFAULT_PLUGINS_BLOCK = """plugins:
  - search
"""


def publish_release_notes_pages(
    *,
    pages_by_lang: Dict[str, str],
    docs_dir: Path = Path("docs"),
    basename: str = "release-notes",
) -> None:
    """
    Write markdown pages under docs/ as:
      docs/release-notes.<lang>.md
      Notes:
    - Output filenames are stable: release-notes.<lang>.md
    - This makes it easy to diff/review and to generate deterministic MkDocs nav entries.
    """
    docs_dir.mkdir(parents=True, exist_ok=True)

    # Write one page per language. Language codes come from TARGET_LANGS configuration.
    for lang_code, md in pages_by_lang.items():
        (docs_dir / f"{basename}.{lang_code}.md").write_text(md, encoding="utf-8")


# Keep a simple landing page so the site is self-explanatory for reviewers.
# Only created if missing, so users can replace it with custom content.
def ensure_index_page(docs_dir: Path = Path("docs")) -> None:
    """
    Create a simple landing page if it doesn't exist.
    """
    docs_dir.mkdir(parents=True, exist_ok=True)
    idx = docs_dir / "index.md"
    if idx.exists():
        return
    idx.write_text(
        "# Release Notes Automation\n\n"
        "This site is generated by an automated workflow:\n\n"
        "1. Harvest changes between two Git refs\n"
        "2. Rule-based filtering (exclude noise)\n"
        "3. LLM-assisted disambiguation (only for ambiguous items)\n"
        "4. Human-in-the-loop review via `review.json`\n"
        "5. Rendering to Markdown + optional translation\n\n"
        "Use the navigation menu to browse release notes.\n",
        encoding="utf-8",
    )


def write_mkdocs_yml(
    *,
    language_codes: List[str],
    out_path: Path = Path("mkdocs.yml"),
    site_name: str = "Release Notes (Automation Demo)",
    site_description: str = "Auto-generated release notes with human-in-the-loop review",
    basename: str = "release-notes",
    language_labels: Optional[Dict[str, str]] = None,
    theme_block: str = DEFAULT_THEME_BLOCK,
    md_extensions_block: str = DEFAULT_MD_EXTENSIONS_BLOCK,
    plugins_block: str = DEFAULT_PLUGINS_BLOCK,
) -> None:
    """
    Generate mkdocs.yml with nav entries for each language.
    Writes mkdocs.yml in project root by default.
    Design choices:
    - Deterministic ordering: keep input order but ensure English first (base page).
    - Language labels are overridable; unknown codes fall back to the code itself.
    """
    if language_labels is None:
        # fallback labels (you can extend freely)
        language_labels = {
            "en": "English",
            "it": "Italian",
            "fr": "French",
            "de": "German",
            "es": "Spanish",
        }

    # Ensure deterministic order: keep the passed order, but put 'en' first if present
    langs = list(language_codes)
    if "en" in langs:
        langs = ["en"] + [c for c in langs if c != "en"]

    # Build nav entries dynamically from available languages (configuration-driven publishing).
    nav_lines = ["nav:", "  - Home: index.md", "  - Release Notes:"]
    for code in langs:
        label = language_labels.get(code, code)
        nav_lines.append(f"      - {label}: {basename}.{code}.md")

    # Compose final mkdocs.yml content
    yml = (
        f"site_name: {site_name}\n"
        f"site_description: {site_description}\n"
        f"{theme_block}\n"
        + "\n".join(nav_lines)
        + "\n\n"
        + md_extensions_block
        + "\n"
        + plugins_block
    )

    out_path.write_text(yml, encoding="utf-8")
